### PR TITLE
Remove Cacheray APIs and make runtime auto-init

### PR DESCRIPTION
**Pull request by kimgr**
This is a big total diff, but the individual commits are mostly small and mechanical.

Once this is in place, it's easier to fix up stuff like options parsing from environment, proper reentrancy handling, etc.

### CODE REVIEW

**Comment by kimgr** [comment]
I think it would be nicer to squash all the test cleanups and all the testbench cleanups into two commits instead of doing them as tiny increments. Will push an update with that.

**Comment by kimgr** [comment]
Done. Please take a look.

**Comment by kimgr** [comment]
@hannesastrom Would be nice if you could test this on your machine to make sure the testbench stuff still works. I couldn't work up the energy to rebuild all of LLVM :).

**Comment by hannesastrom** [comment]
Haha, I see you've been busy. I'll try to check it on my computer tomorrow.

**Pull request merged**
